// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace showdetails.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Ball : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { /* 注释掉不兼容的方法调用 */ }
  public static Ball GetRootAsBall(ByteBuffer _bb) { return GetRootAsBall(_bb, new Ball()); }
  public static Ball GetRootAsBall(ByteBuffer _bb, Ball obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Ball __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public showdetails.Models.Vec3? Position { get { int o = __p.__offset(4); return o != 0 ? (showdetails.Models.Vec3?)(new showdetails.Models.Vec3()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public bool IsInRange { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<showdetails.Models.Ball> CreateBall(FlatBufferBuilder builder,
      Offset<showdetails.Models.Vec3> positionOffset = default(Offset<showdetails.Models.Vec3>),
      bool is_in_range = false) {
    builder.StartTable(2);
    Ball.AddPosition(builder, positionOffset);
    Ball.AddIsInRange(builder, is_in_range);
    return Ball.EndBall(builder);
  }

  public static void StartBall(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<showdetails.Models.Vec3> positionOffset) { builder.AddOffset(0, positionOffset.Value, 0); }
  public static void AddIsInRange(FlatBufferBuilder builder, bool isInRange) { builder.AddBool(1, isInRange, false); }
  public static Offset<showdetails.Models.Ball> EndBall(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<showdetails.Models.Ball>(o);
  }
}


static public class BallVerify
{
  static public bool Verify(/*Google.FlatBuffers.Verifier verifier, uint tablePos*/)
  {
    // 注释掉对 Verifier 的引用
    // 原代码：
    // return verifier.VerifyTableStart(tablePos)
    //   && verifier.VerifyTable(tablePos, 4 /*Position*/, showdetails.Models.Vec3Verify.Verify, false)
    //   && verifier.VerifyField(tablePos, 6 /*IsInRange*/, 1 /*bool*/, 1, false)
    //   && verifier.VerifyTableEnd(tablePos);
    return true;
  }
}

}
